name: bmi_calculator
description: "A simple BMI Calculator app built with Flutter."
# This line prevents the package from being accidentally published to pub.dev.
publish_to: 'none'

# Version and build number for the application.
version: 1.0.0+1

# Environment settings.
environment:
  sdk: '>=3.3.0 <4.0.0' # Compatible Dart SDK version range

# List of dependencies your project requires to work.
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6 # iOS-style icons
  font_awesome_flutter: ^10.7.0 # Font Awesome icons for Flutter

# List of development dependencies (for testing, linting, etc.)
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0 # Recommended linting rules for Flutter projects

# Flutter-specific settings
flutter:
  uses-material-design: true # Includes Material Design icons by default

  # Define assets for your project. Uncomment to add custom assets like images.
  # assets:
  #   - images/sample_image.png

  # Define custom fonts for your project. Uncomment to add custom fonts.
  # fonts:
  #   - family: MyCustomFont
  #     fonts:
  #       - asset: fonts/MyCustomFont-Regular.ttf

  # Any other configurations specific to Flutter.
