name: bmi_calculator
description: "A simple Flutter project."
publish_to: 'none' # Prevents accidental publication to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0' # Compatible Dart SDK version range

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6 # iOS-style icons
  font_awesome_flutter: ^10.7.0 # Font Awesome icons for Flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^3.0.0

flutter_launcher_icons:
      android: "launcher_icon"

      image_path: "assets/icon.png"

   # Linting rules for Flutter projects

flutter:
  uses-material-design: true # Includes Material Design icons by default

  # Optional assets configuration
  # assets:
  #   - images/a_dot_burr.jpeg

  # Custom fonts configuration (if needed)
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
